// Missing Name
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "number": "12345651646"
}

###
// Missing Number
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Test person"
}

###
// Name too short
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Ad",
    "number": "12345651646"
}

###
// Bad number 
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Random Person",
    "number": "12345651646"
}
###
// Add 
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Random Persono",
    "number": "040-22334455"
}