//Add working correctly
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "another notes bites the dust",
  "important": false,
  "userId": "67a66e34f2538c466a4af30e"
}

###
//Missing content
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "important": false
}
###
//Note too short
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "res",
  "important": false
}
